config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "about" => "homes#about" , as: "about"
  resources :users
  resources :breweries
  resource :relationships, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brewery.rb
class Brewery < ApplicationRecord
    belongs_to :user
    attachment :image
    has_many :favorites, dependent: :destroy

    validates :brewery_name, presence: true
    validates :prefecture_id, presence: true
    validates :comment, presence: true, length: { maximum: 200 }

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture

  def self.search(search)
    return Brewery.all unless search
    Brewery.where(prefecture_id: search)
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :brewery
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image

  validates :name, presence: true, uniqueness: true,
    length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :breweries, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user
  has_many :favorites, dependent: :destroy

  def follow(other_user)
    return if self == other_user
    relationships.find_or_create_by!(follow: other_user)
  end

  def following?(user)
    followings.include?(user)
  end

  def unfollow(relathinoship_id)
    relationships.find_by(follow: relathinoship_id).destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_log_in_path_for(resource)
    user_path(current_path)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    @breweries = Brewery.search(params[:prefecture_id]).all.page(params[:page]).per(8)
  end

  def show
    @brewery = Brewery.find(params[:id])
    @user = @brewery.user
  end

  def edit
    @brewery = Brewery.find(params[:id])
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.new(brewery_params)
    @brewery.user_id = current_user.id
      if @brewery.save
        flash[:notice] = "Brewery is successfully created."
        redirect_to breweries_path
      else
        @breweries = Brewery.all
        @user = current_user
        render :new
      end
  end

  def update
    @brewery = Brewery.find(params[:id])
      if @brewery.update(brewery_params)
        flash[:notice] = "Brewery is successfully updated."
        redirect_to brewery_path(@brewery)
      else
        render :edit
      end
  end

  def destroy
    @brewery = Brewery.find(params[:id])
      if @brewery.destroy
        flash[:notice] = "Brewery is successfully deleted."
        redirect_to user_path(current_user)
      else
        render :show
      end
  end

  private
    def brewery_params
      params.require(:brewery).permit(:brewery_name, :image, :prefecture_id, :address, :star, :comment, :user_id)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @brewery = Brewery.find(params[:format])
    favorite = current_user.favorites.new(brewery_id: @brewery.id)
    favorite.save
  end

  def destroy
    @brewery = Brewery.find(params[:format])
    favorite = current_user.favorites.find_by(brewery_id: @brewery.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @other_user = User.find(params[:follow])
    current_user.follow(@other_user)
  end

  def destroy
    @other_user = User.find(params[:follow])
    current_user.unfollow(@other_user.id)
  end

  private
    def relationship_params
      params.require(:relationship).permit(:relationship, :follow_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).reverse_order
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @breweries = @user.breweries.all.page(params[:page]).per(9)
  end

  def edit
    @user = User.find(params[:id])
      if @user == current_user
        render "edit"
      else
        redirect_to user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
      if @user != current_user
        redirect_to user_path(current_user) and return
      end
      if @user.update(user_params)
        flash[:notice] = "User is successfully updated."
        redirect_to user_path(current_user)
      else
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id])
      if @user.destroy
        flash[:notice] = "User is successfully deleted."
        redirect_to root_path
      else
        render :edit
      end
  end

private
  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/breweries/edit.html.erb
<div class="background">
  <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>投稿編集</h2>
            <% if @brewery.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= I18n.t("errors.messages.not_saved",
                               count: @brewery.errors.count,
                               resource: @brewery.class.model_name.human.downcase)
                     %>
                  </h2>
                  <ul>
                    <% @brewery.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <%= form_with model:@brewery, local: true do |f| %>
                <div class="form-group">
                  <label for="brewery_image"></label>
                  <div><%= f.attachment_field :image, placeholder:"ブルワリー画像"%></div>
                </div>
                <div class="form-group">
                  <label for="brewery_title">ブルワリー</label>
                  <div><%= f.text_field :brewery_name %></div>
                </div>
                <label for="brewery_prefecture">都道府県</label>
                <div><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %></div>
                <div class="form-group">
                  <label for="address">住所</label>
                  <div><%= f.text_field :address %></div>
                </div>
                <div class="form-group">
                  <label for="brewery_comment">コメント</label>
                  <div><%= f.text_area :comment %></div>
                </div>
                <div class="field" id="star">
                  <%= f.label :star, "星評価：" %>
                  <%= f.hidden_field :star, id: :review_star %>
                  <script>
                    $('#star').raty({
                      size     : 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      scoreName: 'brewery[star]',
                      half: true,
                    });
                  </script>
                </div>
                <div class="form-group">
                  <div><%= f.submit '変更を保存する', class: "btn btn-success"%></div>
                </div>
                <div class="form-group">
                  <%= link_to "詳細", brewery_path(@brewery), class: "btn btn-secondary" %>
                  <%= link_to "戻る", user_path(current_user), class: "btn btn-secondary" %>
                </div>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/breweries/index.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="background">
  <div class="container-fluid">
    <div class="row">
      <div class="col-auto ml-1 mt-2">
        <%= form_with url: breweries_path, method: :get, local: true do |f| %>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %>
          <%= f.submit "検索", class: "search_submit" %>
        <% end %>
        <%= link_to new_brewery_path, method: :get do %>
          <i class="fas fa-plus-circle fa-4x"></i>
        <% end %>
        <h2>Breweries</h2>
      </div>
    </div>
          <div class="row mx-auto">
            <div class="col-11 mx-auto">
              <div class="d-flex align-content-start flex-wrap mt-4">
                <% @breweries.each do |brewery| %>
                   <div class="mx-5 my-4 out-line">
                    <div>
                      <%= link_to brewery_path(brewery.id) do %>
                      <%= attachment_image_tag brewery, :image, size: "200x200", fallback: "no_image.jpg"%>
                      <% end %>
                    </div>
                    <div class="text-center"><%= brewery.brewery_name %></div>
                    <div class="text-center"><%= brewery.prefecture.try(:name) %></div>
                    <div class="text-center"><%= brewery.user.name %></div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <%= paginate @breweries %>
  </div>
</div>

app/views/breweries/new.html.erb
<div class="background">
  <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>新規投稿</h1>
              <% if @brewery.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= I18n.t("errors.messages.not_saved",
                               count: @brewery.errors.count,
                               resource: @brewery.class.model_name.human.downcase)
                     %>
                  </h2>
                  <ul>
                    <% @brewery.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <%= form_with model: @brewery, local:true do |f| %>
                <div class="form-group">
                  <label for="image"></label>
                  <div><%= f.attachment_field :image %></div>
                </div>
                <div class="form-group">
                  <label for="brewery_title">ブルワリー名</label>
                  <div><%= f.text_field :brewery_name %></div>
                </div>
                <label for="brewery_prefecture">都道府県</label>
                <div><%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %></div>
                <div class="form-group">
                  <label for="address">住所</label>
                  <div><%= f.text_field :address %></div>
                </div>
                <div class="form-group">
                  <label for="brewery_comment">コメント</label>
                  <div><%= f.text_area :comment %></div>
                </div>
                <div class="field" id="star">
                  <%= f.label :star, "星評価：" %>
                  <%= f.hidden_field :star, id: :review_star %>
                  <script>
                    $('#star').raty({
                      size     : 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      scoreName: 'brewery[star]',
                      half: true,
                    });
                  </script>
                </div>
                <div class="form-group">
                  <%= f.submit '投稿', class: "btn btn-success" %>
                </div>
              <% end %>
          </div>
        </div>
    </div>
</div>

app/views/breweries/show.html.erb
<main>
  <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <div class="background">
    <div class="container px-5 px-sm-0">
      <div class="row">
          <div class="col-md-6">
            <h2>投稿詳細</h2>
              <div><%= attachment_image_tag @brewery, :image, size: "400x400", fallback: "no_image.jpg"%></div>
              <br>
              <div>ブルワリー：<%= @brewery.brewery_name %></div>
              <br>
              <div>地域：<%= @brewery.prefecture.try(:name) %></div>
              <br>
              <div>投稿者：<%= link_to "#{@user.name}", user_path(@user) %></div>
              <br>
              <div id="likes_buttons_<%= @brewery.id %>">
               <%= render partial: 'favorites/like', locals: { brewery: @brewery} %>
              </div>
          </div>
          <div class="col-md-6">
                <script type="text/javascript">
                  function initMap() {
                    var test ={lat: <%= @brewery.latitude %>, lng: <%= @brewery.longitude %>};
                    var map = new google.maps.Map(document.getElementById('map'), {
                              zoom: 15,
                              center: test
                              });
                    var transitLayer = new google.maps.TransitLayer();
                    transitLayer.setMap(map);

                    var contentString = '<p class="infowindow">住所：<%= @brewery.address %></p>';
                    var infowindow = new google.maps.InfoWindow({
                      content: contentString
                    });
                    var marker = new google.maps.Marker({
                                  position:test,
                                  map: map,
                                  title: contentString
                                 });
                     marker.addListener('click', function() {
                       console.log("contentString: ", contentString);
                       infowindow.open(map, marker);
                     });
                  }
                </script>
                <script async defer
                              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyA_da_1uPYkmS4kcibKdzZtJ03q35f59pU&callback=initMap">
                </script>
                <style type="text/css">
                  #map { height: 400px;
                         width: 70%;}
                </style>
                <div id="map"></div>
                <br>
                <div>コメント：<%= @brewery.comment %></div>
                <br>
                <div class="relative-post-evaluation">
                  <span>評価：</span>
                  <span id="star-rate-<%= @brewery.id %>"></span>
                  <script>
                    $('#star-rate-<%= @brewery.id %>').raty({
                      size: 36,
                      starOff: "<%= asset_path('star-off.png') %>",
                      starOn: "<%= asset_path('star-on.png') %>",
                      starHalf: "<%= asset_path('star-half.png') %>",
                      half: true,
                      readOnly: true,
                      score: <%= @brewery.star %>,
                    });
                  </script>
                  <%= @brewery.star %>
                </div>
                <br>
              <% if @user.id == current_user.id %>
                <%= link_to "編集", edit_brewery_path(@brewery), class: "btn btn-sm btn-success edit_book_14995"%>
                <%= link_to "削除", brewery_path(@brewery), method: :delete, data: {confirm: "本当に削除しますか?"}, class: "btn btn-sm btn-danger destroy_book_14995"%></td>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</main>

app/views/favorites/_like.html.erb
<% if @brewery.favorited_by?(current_user) %>
                <p>
                  <%= link_to favorites_path(@brewery), method: :delete, remote: true do %>
                    ♥<%= @brewery.favorites.count %> いいね
                  <% end %>
                </p>
              <% else %>

                <p>
                  <%= link_to favorites_path(@brewery), method: :post, remote: true do %>
                    ♡<%= @brewery.favorites.count %> いいね
                  <% end %>
                </p>
              <% end %>

app/views/favorites/create.js.erb
$('#likes_buttons_<%= @brewery.id %>').html("<%= j(render partial: 'favorites/like', locals: {brewery: @brewery}) %>");

app/views/favorites/destroy.js.erb
$('#likes_buttons_<%= @brewery.id %>').html("<%= j(render partial: 'favorites/like', locals: {brewery: @brewery}) %>");

app/views/homes/about.html.erb
<main>
  <div class="wrapper">
  <div class="about">
  <div class="box" >
    <div class="img01"></div>
    <div class="img02"></div>
    <div class="img03"></div>
    <div class="img04"></div>
 </div>
 </div>

  <div class="topText">
    <h2 class=>Hop Holicって？</h2>
    <br>
      <p>その名の通り「ホップ（ビールの原料）中毒」という意味。</p>
        <p>Hop Holicではビール好きがお勧めブルワリーのクラフトビールを紹介しています。</p>
        <p>どこのブルワリーがどんなビールを作っているのかをシェアし、</p>
        <p>クラフトビール文化を日本に広めていくことを目的としています。</p>
    <br>
      <h2>Hop Holicの使い方</h2>
      <br>
        <p>1. マイページを作成</p>
        <p>2. みんなのブルワリーの投稿を閲覧（都道府県で検索可能）</p>
        <p>3. 自分がオススメしたいブルワリーを投稿</p>
        <p>4. お気に入りの投稿者をフォロー</p>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="wrapper">
  <div class="box" >
    <div class="img01"></div>
    <div class="img02"></div>
    <div class="img03"></div>
    <div class="img04"></div>
 </div>

  <div class="topText">
    <h1>Hop Holic</h1>
    <h3>- Craft Beer & Brewery -</h3>
  </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hopholic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-white">
       <div class="container">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item1">
              <%= link_to "Hop Holic", root_path, data: {"turbolinks" => false}, class: 'nav-link text-dark' %>
            </li>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                </ul>
                  <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                        <%= link_to "My page", user_path(current_user.id), class: 'nav-link text-dark' %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "Brewery", breweries_path, class: 'nav-link text-dark' %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "User", users_path, class: 'nav-link text-dark' %>
                      </li>
                      <li class="nav-item">
                        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                      </li>
                    </ul>
                  </div>
          <% else %>
            <li class="nav-item1">
              <%= link_to "Hop Holic", root_path, data: {"turbolinks" => false}, class: 'nav-link text-dark' %>
            </li>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                </ul>
                  <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                         <%= link_to "About", about_path, data: {"turbolinks" => false}, class: 'nav-link text-dark' %>
                      </li>
                      <li class="nav-item">
                         <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-dark' %>
                      </li>
                      <li class="nav-item">
                         <%= link_to "Log in", user_session_path, class: 'nav-link text-dark' %>
                      </li>
                    </ul>
                  </div>
          <% end %>
        </div>
      </div>
    </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>© All rights reserved by Hop Holic.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<%= button_to 'フォロー', relationships_path(follow: user), remote: true %>

app/views/relationships/_unfollow_button.html.erb
<%= button_to 'フォロー解除', relationships_path(follow: user), method: :delete, remote: true %>

app/views/relationships/create.js.erb
$("#follow-button-<%= @other_user.id %>").html("<%= j(render 'unfollow_button', user: @other_user) %>")

app/views/relationships/destroy.js.erb
$("#follow-button-<%= @other_user.id %>").html("<%= j(render 'follow_button', user: @other_user) %>")

app/views/users/index.html.erb
<main>
  <div class="background">
    <div class="container px-5 px-sm-0">
      <div class="row">
          <div class="col-md-3">
            <h2></h2>
            <%= attachment_image_tag @user, :image, size: "60x60", fallback: "no_image.jpg"%>
              <table class="table">
                <tbody>
                  <tr></tr>
                  <tr>
                    <th>名前</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                    <th>自己紹介</th>
                    <th><%= @user.introduction %></th>
                  </tr>
                </tbody>
              </table>
              <div class="row">
                <%= link_to edit_user_path(@user), class: "btn btn-outline-light btn-block", method: :get do %>
                  <i class="fas fa-user-cog"></i>
                <% end %>
              </div>
          </div>
          <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>名前</th>
                            <th>自己紹介</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                        <tr>
                            <td>
                              <%= link_to user_path(user.id) do %>
                              <%= attachment_image_tag user, :image, size: "60x60", fallback: "no_image.jpg"%>
                              <% end %>
                            </td>
                            <td><%= user.name %></td>
                            <td><%= user.introduction %></td>
                            <td>
                              <%if current_user != user %>
                              <div id="follow-button-<%= user.id %>" >
                                 <% if current_user.following?(user) %>
                                    <%= render 'relationships/unfollow_button', user: user %>
                                 <% else %>
                                    <%= render 'relationships/follow_button', user: user %>
                                  <% end %>
                              </div>
                              <% end %>
                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
                <%= paginate @users %>
            </div>
        </div>
    </div>
  </div>  
</main>

app/views/users/show.html.erb
<main>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
  <div class="background">
    <div class="container px-5 px-sm-0">
      <div class="row">
          <div class="col-md-3">
            <h2></h2>
            <%= attachment_image_tag @user, :image, size: "60x60", fallback: "no_image.jpg"%>
              <table class="table">
                <tbody>
                  <tr></tr>
                  <tr>
                    <th>名前</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                    <th>自己紹介</th>
                    <th><%= @user.introduction %></th>
                  </tr>
                </tbody>
              </table>
              <div class="row">
                <% if @user.id == current_user.id %>
                  <%= link_to edit_user_path(@user), class: "btn btn-outline-light btn-block", method: :get do %>
                    <i class="fas fa-user-cog"></i>
                  <% end %>
                <% end %>
              </div>
          </div>
            <div class="col-md-8 offset-md-1"> 
              <div class="d-flex align-content-start flex-wrap mt-4">
                  <% @breweries.each do |brewery| %>
                    <div class="mx-5 my-4 out-line">
                      <div>
                        <%= link_to brewery_path(brewery.id) do %>
                        <%= attachment_image_tag brewery, :image, size: "150x150", fallback: "no_image.jpg"%>
                        <% end %>
                      </div>
                        <div class="text-center"><%= brewery.brewery_name %></div>
                        <div class="text-center"><%= brewery.prefecture.try(:name) %></div>
                      </div>
                  <% end %>
                  <%= paginate @breweries %>
                </div>
              </div>
        </div>
      </div>
    </div>  
</main>